global:
  log_level: info
  client_logs_to_stdout: true
  docker_network: benchmarkoor
  cleanup_on_start: false

benchmark:
  results_dir: ./results
  generate_results_index: true
  generate_suite_stats: true
  tests:
    # Comment out the "filter" if you want to run the full suite
    filter: "bn128"
    source:
      eest_fixtures:
        github_repo: ethereum/execution-spec-tests
        github_release: benchmark@v0.0.7

client:
  config:
    drop_memory_caches: "steps"
    # Set resource limits, for example, as per https://eips.ethereum.org/EIPS/eip-7870
    # resource_limits:
    #   cpuset_count: 4
    #   memory: "32g"
    #   swap_disabled: true

  instances:
    - id: nethermind
      client: nethermind
    - id: geth
      client: geth
    - id: reth
      client: reth
    - id: erigon
      client: erigon
    - id: besu
      client: besu

api:
  server:
    listen: ":9090"
    cors_origins:
      - "*"
  auth:
    session_ttl: 24h
    basic:
      enabled: true
      users:
        - username: admin
          password: changeme
          role: admin
  database:
    driver: sqlite
    sqlite:
      path: /app/data/benchmarkoor.db

  #storage:
  #  s3:
  #    enabled: true
  #    endpoint_url: ${S3_ENDPOINT_URL}
  #    region: us-east-1
  #    bucket: benchmarkoor-results
  #    access_key_id: ${AWS_ACCESS_KEY_ID}
  #    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  #    presigned_urls:
  #      expiry: 1h
  #    discovery_paths:
  #      - results
