services:
  benchmarkoor:
    image: ethpandaops/benchmarkoor:dev
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
     # Required for dropping memory caches between tests (config.yaml#client.config.drop_memory_caches)
      - SYS_ADMIN
    environment:
      - BENCHMARKOOR_GLOBAL_DROP_CACHES_PATH=/host_drop_caches
      - BENCHMARKOOR_GLOBAL_CPU_SYSFS_PATH=/host_sys_cpu
      - BENCHMARKOOR_GLOBAL_DIRECTORIES_TMP_DATADIR=${PWD}/tmp/data
      - BENCHMARKOOR_GLOBAL_DIRECTORIES_TMP_CACHEDIR=${PWD}/tmp/cache
      - BENCHMARKOOR_BENCHMARK_RESULTS_OWNER=${USER_UID}:${USER_GID}
    volumes:
      # The docker socket is required to interact with docker containers
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # The cgroups path is recommended when on Linux systems to fetch system metrics
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # Required for dropping memory caches between tests (config.yaml#client.config.drop_memory_caches)
      - /proc/sys/vm/drop_caches:/host_drop_caches
      # Required for CPU frequency control (config.yaml#client.config.resource_limits.cpu_freq)
      - /sys/devices/system/cpu:/host_sys_cpu
      # Config file
      - ./${BENCHMARKOOR_CONFIG:-config.example.docker.yaml}:/app/config.yaml:ro
      # Temp directory (For fetching temporary files and node data dirs)
      - ${PWD}/tmp:${PWD}/tmp
      # Results directory
      - ./results:/app/results
    working_dir: /app
    command: ["run", "--config", "/app/config.yaml"]
    network_mode: host

  ui:
    image: ethpandaops/benchmarkoor-ui:dev
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "${UI_PORT:-8080}:80"
    volumes:
      - ./results:/usr/share/nginx/html/results:ro
    depends_on:
      - benchmarkoor
