services:
  benchmarkoor:
    image: ethpandaops/benchmarkoor:dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BENCHMARKOOR_GLOBAL_DIRECTORIES_TMP_DATADIR=${PWD}/tmp/data
      - BENCHMARKOOR_GLOBAL_DIRECTORIES_TMP_CACHEDIR=${PWD}/tmp/cache
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config.example.docker.yaml:/app/config.yaml:ro
      - ${PWD}/tmp:${PWD}/tmp
      - ./results:/app/results
    working_dir: /app
    command: ["run", "--config", "/app/config.yaml"]
    network_mode: host

  ui:
    image: ethpandaops/benchmarkoor-ui:dev
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8080:80"
    volumes:
      - ./results:/usr/share/nginx/html/results:ro
    depends_on:
      - benchmarkoor
