global:
  log_level: info

runner:
  client_logs_to_stdout: true
  cleanup_on_start: false
  # github_token: # Only needed to fetch github action artifacts when using eest_fixtures source with artifacts

  benchmark:
    results_dir: ./results
    #results_owner: "1000:1000" # Depending if you run benchmarkoor with sudo, you might want the results to be owned by your own user
    generate_results_index: true
    generate_suite_stats: true
    system_resource_collection_enabled: false   # This works well if you're on a Linux system via cgroups. In that case, set to "true"
                                                # If you're on a Mac, it will be way slower because we'll have to collect
                                                # the system metrics over the docker api, which will make your run slow, but won't
                                                # affect the benchmark times.

    tests:
      filter: "bn128" # Comment this out if you want to run the full test suite
      source:
        # Run using github release fixtures.
        eest_fixtures:
          github_repo: ethereum/execution-spec-tests
          github_release: benchmark@v0.0.7
        # Run using github actions artifact fixtures
        # (Requires local "gh" cli. Or setting runner.github_token)
        # eest_fixtures:
        #  github_repo: ethereum/execution-specs
        #  genesis_artifact_name:  benchmark_genesis_benchmark_fast
        #  fixtures_artifact_name: fixtures_benchmark_fast

  client:
    config:
      # drop_memory_caches: "steps" # Remove the comment if you want to drop memory caches between step execution
                                    # Note that it will require sudo (root) access for this. It also only works on Linux.

  instances:
    - id: nethermind
      client: nethermind
    - id: geth
      client: geth
      image: ethpandaops/geth:master
    - id: reth
      client: reth
    - id: erigon
      client: erigon
    - id: besu
      client: besu
