name: Check - CI (Github Action)

on:
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Benchmarkoor Test
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-ref: ${{ github.event.pull_request.head.sha }}
          run-args: '--log-level=debug'
          run-config: |
            global:
              log_level: debug
              client_logs_to_stdout: true
              cleanup_on_start: true

            benchmark:
              system_resource_collection_enabled: true
              tests:
                filter: "bn128"
                source:
                  eest_fixtures:
                    github_repo: ethereum/execution-spec-tests
                    github_release: benchmark@v0.0.5

            client:
              config:
                drop_memory_caches: "steps"
              instances:
                - id: geth
                  client: geth
